version: '3.2'

services:
  postgres:
    container_name: arena_db
    image: postgres:16.1
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arena_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - arena_data:/var/lib/postgresql/data/

volumes:
  arena_data:
